name: Blazor WASM WebApp CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'release-*.*.*'

env:
  PROJECT_DIR: 'src/BlazorDemoApp/'
  PROJECT_FILE: 'src/BlazorDemoApp/BlazorDemoApp.csproj'
  WWWROOT_PATH: 'publish/wwwroot'
  ARTIFACT: 'blazor-wasm-artifacts'

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_PUBLISH_PATH: './publish'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: View file structure
        run: tree /F

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore NuGet packages
        run: dotnet restore "${{ env.PROJECT_FILE }}" --verbosity quiet

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_FILE }}" -c Release -o ${{ env.BUILD_PUBLISH_PATH }} --no-restore --verbosity quiet

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.BUILD_PUBLISH_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Download the release artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT }}
        path: release

    - name: Change base-tag in index.html from / to Demo-Site
      run: sed -i 's/<base href="\/" \/>/<base href="\/Demo-Site\/" \/>/g' release/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
